### ISSUE TITLE
save as .ply

### ISSUE THREAD

**Issue by C00reNUT** [pablovela5620/monoprior#2]
Hello,
do you think it is possible to save the results as ply model?

**Comment by pablovela5620** [comment]
It is definintely possible! I don't currently have that functionality but you could use something like https://trimesh.org/ to save the output pointcloud from here https://github.com/pablovela5620/monoprior/blob/2c6c8e026a1fa6659cbe1b9ea8ad07ebf08abdfe/monopriors/depth_utils.py#L103
